// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Nlb.Outputs
{

    [OutputType]
    public sealed class GetListenerHealthsListenerHealthResult
    {
        /// <summary>
        /// The number of healthy backend servers.
        /// </summary>
        public readonly int HealthyCount;
        /// <summary>
        /// The ID of the listener.
        /// </summary>
        public readonly string ListenerId;
        /// <summary>
        /// The list of backend servers.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetListenerHealthsListenerHealthResultResult> Results;
        /// <summary>
        /// The ID of the server group.
        /// </summary>
        public readonly string ServerGroupId;
        /// <summary>
        /// The status of the server group. Valid values: `Active`, `NoTarget`, `Error`, `Disabled`.
        /// `NoTarget`: The server group does not have any backend servers added, or the server group has closed cross-zone forwarding and there are no backend servers in the zone where the access traffic originates.
        /// `Error`: There are unhealthy backend servers in the server group.
        /// `Active`: All backend servers in the server group are healthy.
        /// `Disabled`: The server group has closed health checks, or the NLB instance associated with the server group is in a stopped state.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// The number of unhealthy backend servers.
        /// </summary>
        public readonly int UnhealthyCount;

        [OutputConstructor]
        private GetListenerHealthsListenerHealthResult(
            int healthyCount,

            string listenerId,

            ImmutableArray<Outputs.GetListenerHealthsListenerHealthResultResult> results,

            string serverGroupId,

            string status,

            int unhealthyCount)
        {
            HealthyCount = healthyCount;
            ListenerId = listenerId;
            Results = results;
            ServerGroupId = serverGroupId;
            Status = status;
            UnhealthyCount = unhealthyCount;
        }
    }
}
