// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rds_postgresql

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/internal"
)

// Use this data source to query detailed information of rds postgresql planned events
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/rds_postgresql"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := rds_postgresql.GetPlannedEvents(ctx, &rds_postgresql.GetPlannedEventsArgs{
//				EventTypes: []string{
//					"VersionUpgrade",
//				},
//				InstanceId:                        pulumi.StringRef("postgres-72715e0d9f58"),
//				InstanceName:                      pulumi.StringRef("test-01"),
//				PlannedSwitchTimeSearchRangeEnd:   pulumi.StringRef("2025-12-15T17:40:53.000Z"),
//				PlannedSwitchTimeSearchRangeStart: pulumi.StringRef("2025-12-01T02:06:53.000Z"),
//				Statuses: []string{
//					"WaitStart",
//					"Running",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetPlannedEvents(ctx *pulumi.Context, args *GetPlannedEventsArgs, opts ...pulumi.InvokeOption) (*GetPlannedEventsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPlannedEventsResult
	err := ctx.Invoke("volcengine:rds_postgresql/getPlannedEvents:getPlannedEvents", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPlannedEvents.
type GetPlannedEventsArgs struct {
	// Event ID.
	EventId *string `pulumi:"eventId"`
	// Event type. Values: VersionUpgrade, HostOffline.
	EventTypes []string `pulumi:"eventTypes"`
	// The id of the PostgreSQL instance.
	InstanceId *string `pulumi:"instanceId"`
	// The name of PostgreSQL instance.
	InstanceName *string `pulumi:"instanceName"`
	// File name where to save data source results.
	OutputFile *string `pulumi:"outputFile"`
	// Time window end for planned execution time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC).
	PlannedBeginTimeSearchRangeEnd *string `pulumi:"plannedBeginTimeSearchRangeEnd"`
	// Time window start for planned execution time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC).
	PlannedBeginTimeSearchRangeStart *string `pulumi:"plannedBeginTimeSearchRangeStart"`
	// Time window end for planned switch time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC).
	PlannedSwitchTimeSearchRangeEnd *string `pulumi:"plannedSwitchTimeSearchRangeEnd"`
	// Time window start for planned switch time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC).
	PlannedSwitchTimeSearchRangeStart *string `pulumi:"plannedSwitchTimeSearchRangeStart"`
	// Operation event status. Values: Canceled, WaitStart, WaitSwitch, Running, Running_BeforeSwitch, Running_Switching, Running_AfterSwitch, Success, Failed, Timeout, Rollbacking, RollbackFailed.
	Statuses []string `pulumi:"statuses"`
}

// A collection of values returned by getPlannedEvents.
type GetPlannedEventsResult struct {
	// Event ID.
	EventId *string `pulumi:"eventId"`
	// Event type.
	EventTypes []string `pulumi:"eventTypes"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Instance ID.
	InstanceId *string `pulumi:"instanceId"`
	// Instance name.
	InstanceName                     *string `pulumi:"instanceName"`
	OutputFile                       *string `pulumi:"outputFile"`
	PlannedBeginTimeSearchRangeEnd   *string `pulumi:"plannedBeginTimeSearchRangeEnd"`
	PlannedBeginTimeSearchRangeStart *string `pulumi:"plannedBeginTimeSearchRangeStart"`
	// Planned events list.
	PlannedEvents                     []GetPlannedEventsPlannedEvent `pulumi:"plannedEvents"`
	PlannedSwitchTimeSearchRangeEnd   *string                        `pulumi:"plannedSwitchTimeSearchRangeEnd"`
	PlannedSwitchTimeSearchRangeStart *string                        `pulumi:"plannedSwitchTimeSearchRangeStart"`
	// Operation event status.
	Statuses []string `pulumi:"statuses"`
	// The total count of query.
	TotalCount int `pulumi:"totalCount"`
}

func GetPlannedEventsOutput(ctx *pulumi.Context, args GetPlannedEventsOutputArgs, opts ...pulumi.InvokeOption) GetPlannedEventsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetPlannedEventsResult, error) {
			args := v.(GetPlannedEventsArgs)
			r, err := GetPlannedEvents(ctx, &args, opts...)
			var s GetPlannedEventsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetPlannedEventsResultOutput)
}

// A collection of arguments for invoking getPlannedEvents.
type GetPlannedEventsOutputArgs struct {
	// Event ID.
	EventId pulumi.StringPtrInput `pulumi:"eventId"`
	// Event type. Values: VersionUpgrade, HostOffline.
	EventTypes pulumi.StringArrayInput `pulumi:"eventTypes"`
	// The id of the PostgreSQL instance.
	InstanceId pulumi.StringPtrInput `pulumi:"instanceId"`
	// The name of PostgreSQL instance.
	InstanceName pulumi.StringPtrInput `pulumi:"instanceName"`
	// File name where to save data source results.
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
	// Time window end for planned execution time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC).
	PlannedBeginTimeSearchRangeEnd pulumi.StringPtrInput `pulumi:"plannedBeginTimeSearchRangeEnd"`
	// Time window start for planned execution time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC).
	PlannedBeginTimeSearchRangeStart pulumi.StringPtrInput `pulumi:"plannedBeginTimeSearchRangeStart"`
	// Time window end for planned switch time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC).
	PlannedSwitchTimeSearchRangeEnd pulumi.StringPtrInput `pulumi:"plannedSwitchTimeSearchRangeEnd"`
	// Time window start for planned switch time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC).
	PlannedSwitchTimeSearchRangeStart pulumi.StringPtrInput `pulumi:"plannedSwitchTimeSearchRangeStart"`
	// Operation event status. Values: Canceled, WaitStart, WaitSwitch, Running, Running_BeforeSwitch, Running_Switching, Running_AfterSwitch, Success, Failed, Timeout, Rollbacking, RollbackFailed.
	Statuses pulumi.StringArrayInput `pulumi:"statuses"`
}

func (GetPlannedEventsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPlannedEventsArgs)(nil)).Elem()
}

// A collection of values returned by getPlannedEvents.
type GetPlannedEventsResultOutput struct{ *pulumi.OutputState }

func (GetPlannedEventsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPlannedEventsResult)(nil)).Elem()
}

func (o GetPlannedEventsResultOutput) ToGetPlannedEventsResultOutput() GetPlannedEventsResultOutput {
	return o
}

func (o GetPlannedEventsResultOutput) ToGetPlannedEventsResultOutputWithContext(ctx context.Context) GetPlannedEventsResultOutput {
	return o
}

// Event ID.
func (o GetPlannedEventsResultOutput) EventId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) *string { return v.EventId }).(pulumi.StringPtrOutput)
}

// Event type.
func (o GetPlannedEventsResultOutput) EventTypes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) []string { return v.EventTypes }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetPlannedEventsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Instance ID.
func (o GetPlannedEventsResultOutput) InstanceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) *string { return v.InstanceId }).(pulumi.StringPtrOutput)
}

// Instance name.
func (o GetPlannedEventsResultOutput) InstanceName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) *string { return v.InstanceName }).(pulumi.StringPtrOutput)
}

func (o GetPlannedEventsResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

func (o GetPlannedEventsResultOutput) PlannedBeginTimeSearchRangeEnd() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) *string { return v.PlannedBeginTimeSearchRangeEnd }).(pulumi.StringPtrOutput)
}

func (o GetPlannedEventsResultOutput) PlannedBeginTimeSearchRangeStart() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) *string { return v.PlannedBeginTimeSearchRangeStart }).(pulumi.StringPtrOutput)
}

// Planned events list.
func (o GetPlannedEventsResultOutput) PlannedEvents() GetPlannedEventsPlannedEventArrayOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) []GetPlannedEventsPlannedEvent { return v.PlannedEvents }).(GetPlannedEventsPlannedEventArrayOutput)
}

func (o GetPlannedEventsResultOutput) PlannedSwitchTimeSearchRangeEnd() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) *string { return v.PlannedSwitchTimeSearchRangeEnd }).(pulumi.StringPtrOutput)
}

func (o GetPlannedEventsResultOutput) PlannedSwitchTimeSearchRangeStart() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) *string { return v.PlannedSwitchTimeSearchRangeStart }).(pulumi.StringPtrOutput)
}

// Operation event status.
func (o GetPlannedEventsResultOutput) Statuses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) []string { return v.Statuses }).(pulumi.StringArrayOutput)
}

// The total count of query.
func (o GetPlannedEventsResultOutput) TotalCount() pulumi.IntOutput {
	return o.ApplyT(func(v GetPlannedEventsResult) int { return v.TotalCount }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPlannedEventsResultOutput{})
}
