// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package rds_postgresql

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/internal"
)

// Use this data source to query detailed information of rds postgresql instance ssls
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/rds_postgresql"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := rds_postgresql.GetInstanceSsls(ctx, &rds_postgresql.GetInstanceSslsArgs{
//				DownloadCertificate: pulumi.BoolRef(true),
//				Ids: []string{
//					"postgres-72715e0d9f58",
//					"postgres-0ac38a79fe35",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// Deprecated: volcengine.rds_postgresql.InstanceSsls has been deprecated in favor of volcengine.rds_postgresql.getInstanceSsls
func InstanceSsls(ctx *pulumi.Context, args *InstanceSslsArgs, opts ...pulumi.InvokeOption) (*InstanceSslsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv InstanceSslsResult
	err := ctx.Invoke("volcengine:rds_postgresql/instanceSsls:InstanceSsls", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking InstanceSsls.
type InstanceSslsArgs struct {
	// Whether to include SSL certificate raw bytes for each instance.
	DownloadCertificate *bool `pulumi:"downloadCertificate"`
	// A list of the PostgreSQL instance IDs.
	Ids []string `pulumi:"ids"`
	// A Name Regex of Resource.
	NameRegex *string `pulumi:"nameRegex"`
	// File name where to save data source results.
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by InstanceSsls.
type InstanceSslsResult struct {
	DownloadCertificate *bool `pulumi:"downloadCertificate"`
	// The provider-assigned unique ID for this managed resource.
	Id         string   `pulumi:"id"`
	Ids        []string `pulumi:"ids"`
	NameRegex  *string  `pulumi:"nameRegex"`
	OutputFile *string  `pulumi:"outputFile"`
	// The collection of query.
	Ssls []InstanceSslsSsl `pulumi:"ssls"`
	// The total count of query.
	TotalCount int `pulumi:"totalCount"`
}

func InstanceSslsOutput(ctx *pulumi.Context, args InstanceSslsOutputArgs, opts ...pulumi.InvokeOption) InstanceSslsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (InstanceSslsResult, error) {
			args := v.(InstanceSslsArgs)
			r, err := InstanceSsls(ctx, &args, opts...)
			var s InstanceSslsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(InstanceSslsResultOutput)
}

// A collection of arguments for invoking InstanceSsls.
type InstanceSslsOutputArgs struct {
	// Whether to include SSL certificate raw bytes for each instance.
	DownloadCertificate pulumi.BoolPtrInput `pulumi:"downloadCertificate"`
	// A list of the PostgreSQL instance IDs.
	Ids pulumi.StringArrayInput `pulumi:"ids"`
	// A Name Regex of Resource.
	NameRegex pulumi.StringPtrInput `pulumi:"nameRegex"`
	// File name where to save data source results.
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
}

func (InstanceSslsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceSslsArgs)(nil)).Elem()
}

// A collection of values returned by InstanceSsls.
type InstanceSslsResultOutput struct{ *pulumi.OutputState }

func (InstanceSslsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*InstanceSslsResult)(nil)).Elem()
}

func (o InstanceSslsResultOutput) ToInstanceSslsResultOutput() InstanceSslsResultOutput {
	return o
}

func (o InstanceSslsResultOutput) ToInstanceSslsResultOutputWithContext(ctx context.Context) InstanceSslsResultOutput {
	return o
}

func (o InstanceSslsResultOutput) DownloadCertificate() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v InstanceSslsResult) *bool { return v.DownloadCertificate }).(pulumi.BoolPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o InstanceSslsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v InstanceSslsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o InstanceSslsResultOutput) Ids() pulumi.StringArrayOutput {
	return o.ApplyT(func(v InstanceSslsResult) []string { return v.Ids }).(pulumi.StringArrayOutput)
}

func (o InstanceSslsResultOutput) NameRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceSslsResult) *string { return v.NameRegex }).(pulumi.StringPtrOutput)
}

func (o InstanceSslsResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v InstanceSslsResult) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

// The collection of query.
func (o InstanceSslsResultOutput) Ssls() InstanceSslsSslArrayOutput {
	return o.ApplyT(func(v InstanceSslsResult) []InstanceSslsSsl { return v.Ssls }).(InstanceSslsSslArrayOutput)
}

// The total count of query.
func (o InstanceSslsResultOutput) TotalCount() pulumi.IntOutput {
	return o.ApplyT(func(v InstanceSslsResult) int { return v.TotalCount }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(InstanceSslsResultOutput{})
}
