// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as volcengine from "@pulumi/volcengine";
 *
 * const foo = new volcengine.nat.Gateway("foo", {
 *     billingType: "PostPaid",
 *     description: "This nat gateway auto-created by terraform. ",
 *     natGatewayName: "tf-auto-demo-1",
 *     projectName: "default",
 *     spec: "Medium",
 *     subnetId: "subnet-im67x70vxla88gbssz1hy1z2",
 *     vpcId: "vpc-im67wjcikxkw8gbssx8ufpj8",
 * });
 * ```
 *
 * ## Import
 *
 * NatGateway can be imported using the id, e.g.
 *
 * ```sh
 *  $ pulumi import volcengine:nat/gateway:Gateway default ngw-vv3t043k05sm****
 * ```
 */
export class Gateway extends pulumi.CustomResource {
    /**
     * Get an existing Gateway resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GatewayState, opts?: pulumi.CustomResourceOptions): Gateway {
        return new Gateway(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'volcengine:nat/gateway:Gateway';

    /**
     * Returns true if the given object is an instance of Gateway.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Gateway {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Gateway.__pulumiType;
    }

    /**
     * The billing type of the NatGateway, the value is `PostPaid` or `PrePaid`.
     */
    public readonly billingType!: pulumi.Output<string | undefined>;
    /**
     * The description of the NatGateway.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The name of the NatGateway.
     */
    public readonly natGatewayName!: pulumi.Output<string | undefined>;
    /**
     * The period of the NatGateway, the valid value range in 1~9 or 12 or 24 or 36. Default value is 12. The period unit defaults to `Month`.This field is only effective when creating a PrePaid NatGateway. When importing resources, this attribute will not be imported. If this attribute is set, please use lifecycle and ignoreChanges ignore changes in fields.
     */
    public readonly period!: pulumi.Output<number | undefined>;
    /**
     * The ProjectName of the NatGateway.
     */
    public readonly projectName!: pulumi.Output<string | undefined>;
    /**
     * The specification of the NatGateway. Optional choice contains `Small`(default), `Medium`, `Large`.
     */
    public readonly spec!: pulumi.Output<string | undefined>;
    /**
     * The ID of the Subnet.
     */
    public readonly subnetId!: pulumi.Output<string>;
    /**
     * Tags.
     */
    public readonly tags!: pulumi.Output<outputs.nat.GatewayTag[] | undefined>;
    /**
     * The ID of the VPC.
     */
    public readonly vpcId!: pulumi.Output<string>;

    /**
     * Create a Gateway resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GatewayArgs | GatewayState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GatewayState | undefined;
            resourceInputs["billingType"] = state ? state.billingType : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["natGatewayName"] = state ? state.natGatewayName : undefined;
            resourceInputs["period"] = state ? state.period : undefined;
            resourceInputs["projectName"] = state ? state.projectName : undefined;
            resourceInputs["spec"] = state ? state.spec : undefined;
            resourceInputs["subnetId"] = state ? state.subnetId : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["vpcId"] = state ? state.vpcId : undefined;
        } else {
            const args = argsOrState as GatewayArgs | undefined;
            if ((!args || args.subnetId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'subnetId'");
            }
            if ((!args || args.vpcId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vpcId'");
            }
            resourceInputs["billingType"] = args ? args.billingType : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["natGatewayName"] = args ? args.natGatewayName : undefined;
            resourceInputs["period"] = args ? args.period : undefined;
            resourceInputs["projectName"] = args ? args.projectName : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["subnetId"] = args ? args.subnetId : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["vpcId"] = args ? args.vpcId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Gateway.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Gateway resources.
 */
export interface GatewayState {
    /**
     * The billing type of the NatGateway, the value is `PostPaid` or `PrePaid`.
     */
    billingType?: pulumi.Input<string>;
    /**
     * The description of the NatGateway.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the NatGateway.
     */
    natGatewayName?: pulumi.Input<string>;
    /**
     * The period of the NatGateway, the valid value range in 1~9 or 12 or 24 or 36. Default value is 12. The period unit defaults to `Month`.This field is only effective when creating a PrePaid NatGateway. When importing resources, this attribute will not be imported. If this attribute is set, please use lifecycle and ignoreChanges ignore changes in fields.
     */
    period?: pulumi.Input<number>;
    /**
     * The ProjectName of the NatGateway.
     */
    projectName?: pulumi.Input<string>;
    /**
     * The specification of the NatGateway. Optional choice contains `Small`(default), `Medium`, `Large`.
     */
    spec?: pulumi.Input<string>;
    /**
     * The ID of the Subnet.
     */
    subnetId?: pulumi.Input<string>;
    /**
     * Tags.
     */
    tags?: pulumi.Input<pulumi.Input<inputs.nat.GatewayTag>[]>;
    /**
     * The ID of the VPC.
     */
    vpcId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Gateway resource.
 */
export interface GatewayArgs {
    /**
     * The billing type of the NatGateway, the value is `PostPaid` or `PrePaid`.
     */
    billingType?: pulumi.Input<string>;
    /**
     * The description of the NatGateway.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the NatGateway.
     */
    natGatewayName?: pulumi.Input<string>;
    /**
     * The period of the NatGateway, the valid value range in 1~9 or 12 or 24 or 36. Default value is 12. The period unit defaults to `Month`.This field is only effective when creating a PrePaid NatGateway. When importing resources, this attribute will not be imported. If this attribute is set, please use lifecycle and ignoreChanges ignore changes in fields.
     */
    period?: pulumi.Input<number>;
    /**
     * The ProjectName of the NatGateway.
     */
    projectName?: pulumi.Input<string>;
    /**
     * The specification of the NatGateway. Optional choice contains `Small`(default), `Medium`, `Large`.
     */
    spec?: pulumi.Input<string>;
    /**
     * The ID of the Subnet.
     */
    subnetId: pulumi.Input<string>;
    /**
     * Tags.
     */
    tags?: pulumi.Input<pulumi.Input<inputs.nat.GatewayTag>[]>;
    /**
     * The ID of the VPC.
     */
    vpcId: pulumi.Input<string>;
}
