// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ebs

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/internal"
)

// Use this data source to query detailed information of ebs max extra performances
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/ebs"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := ebs.GetMaxExtraPerformances(ctx, &ebs.GetMaxExtraPerformancesArgs{
//				Size:       pulumi.IntRef(60),
//				VolumeType: pulumi.StringRef("TSSD_TL0"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetMaxExtraPerformances(ctx *pulumi.Context, args *GetMaxExtraPerformancesArgs, opts ...pulumi.InvokeOption) (*GetMaxExtraPerformancesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetMaxExtraPerformancesResult
	err := ctx.Invoke("volcengine:ebs/getMaxExtraPerformances:getMaxExtraPerformances", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMaxExtraPerformances.
type GetMaxExtraPerformancesArgs struct {
	// A Name Regex of Resource.
	NameRegex *string `pulumi:"nameRegex"`
	// File name where to save data source results.
	OutputFile *string `pulumi:"outputFile"`
	// The size of the volume. Unit: GiB.
	Size *int `pulumi:"size"`
	// The id of the volume.
	VolumeId *string `pulumi:"volumeId"`
	// The type of the volume. Valid values: `TSSD_TL0`.
	VolumeType *string `pulumi:"volumeType"`
}

// A collection of values returned by getMaxExtraPerformances.
type GetMaxExtraPerformancesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id         string  `pulumi:"id"`
	NameRegex  *string `pulumi:"nameRegex"`
	OutputFile *string `pulumi:"outputFile"`
	// The collection of query.
	Performances []GetMaxExtraPerformancesPerformance `pulumi:"performances"`
	Size         *int                                 `pulumi:"size"`
	// The total count of query.
	TotalCount int     `pulumi:"totalCount"`
	VolumeId   *string `pulumi:"volumeId"`
	VolumeType *string `pulumi:"volumeType"`
}

func GetMaxExtraPerformancesOutput(ctx *pulumi.Context, args GetMaxExtraPerformancesOutputArgs, opts ...pulumi.InvokeOption) GetMaxExtraPerformancesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetMaxExtraPerformancesResult, error) {
			args := v.(GetMaxExtraPerformancesArgs)
			r, err := GetMaxExtraPerformances(ctx, &args, opts...)
			var s GetMaxExtraPerformancesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetMaxExtraPerformancesResultOutput)
}

// A collection of arguments for invoking getMaxExtraPerformances.
type GetMaxExtraPerformancesOutputArgs struct {
	// A Name Regex of Resource.
	NameRegex pulumi.StringPtrInput `pulumi:"nameRegex"`
	// File name where to save data source results.
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
	// The size of the volume. Unit: GiB.
	Size pulumi.IntPtrInput `pulumi:"size"`
	// The id of the volume.
	VolumeId pulumi.StringPtrInput `pulumi:"volumeId"`
	// The type of the volume. Valid values: `TSSD_TL0`.
	VolumeType pulumi.StringPtrInput `pulumi:"volumeType"`
}

func (GetMaxExtraPerformancesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMaxExtraPerformancesArgs)(nil)).Elem()
}

// A collection of values returned by getMaxExtraPerformances.
type GetMaxExtraPerformancesResultOutput struct{ *pulumi.OutputState }

func (GetMaxExtraPerformancesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMaxExtraPerformancesResult)(nil)).Elem()
}

func (o GetMaxExtraPerformancesResultOutput) ToGetMaxExtraPerformancesResultOutput() GetMaxExtraPerformancesResultOutput {
	return o
}

func (o GetMaxExtraPerformancesResultOutput) ToGetMaxExtraPerformancesResultOutputWithContext(ctx context.Context) GetMaxExtraPerformancesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetMaxExtraPerformancesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetMaxExtraPerformancesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetMaxExtraPerformancesResultOutput) NameRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetMaxExtraPerformancesResult) *string { return v.NameRegex }).(pulumi.StringPtrOutput)
}

func (o GetMaxExtraPerformancesResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetMaxExtraPerformancesResult) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

// The collection of query.
func (o GetMaxExtraPerformancesResultOutput) Performances() GetMaxExtraPerformancesPerformanceArrayOutput {
	return o.ApplyT(func(v GetMaxExtraPerformancesResult) []GetMaxExtraPerformancesPerformance { return v.Performances }).(GetMaxExtraPerformancesPerformanceArrayOutput)
}

func (o GetMaxExtraPerformancesResultOutput) Size() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetMaxExtraPerformancesResult) *int { return v.Size }).(pulumi.IntPtrOutput)
}

// The total count of query.
func (o GetMaxExtraPerformancesResultOutput) TotalCount() pulumi.IntOutput {
	return o.ApplyT(func(v GetMaxExtraPerformancesResult) int { return v.TotalCount }).(pulumi.IntOutput)
}

func (o GetMaxExtraPerformancesResultOutput) VolumeId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetMaxExtraPerformancesResult) *string { return v.VolumeId }).(pulumi.StringPtrOutput)
}

func (o GetMaxExtraPerformancesResultOutput) VolumeType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetMaxExtraPerformancesResult) *string { return v.VolumeType }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetMaxExtraPerformancesResultOutput{})
}
