// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Iam.Outputs
{

    [OutputType]
    public sealed class AllowedIpAddressesAllowedIpAddressResult
    {
        /// <summary>
        /// Whether to enable the IP whitelist.
        /// </summary>
        public readonly bool EnableIpList;
        /// <summary>
        /// The IP whitelist list.
        /// </summary>
        public readonly ImmutableArray<Outputs.AllowedIpAddressesAllowedIpAddressIpListResult> IpLists;
        /// <summary>
        /// The quota of the IP whitelist.
        /// </summary>
        public readonly int Quota;

        [OutputConstructor]
        private AllowedIpAddressesAllowedIpAddressResult(
            bool enableIpList,

            ImmutableArray<Outputs.AllowedIpAddressesAllowedIpAddressIpListResult> ipLists,

            int quota)
        {
            EnableIpList = enableIpList;
            IpLists = ipLists;
            Quota = quota;
        }
    }
}
