// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Tls
{
    [Obsolete(@"volcengine.tls.KafkaConsumers has been deprecated in favor of volcengine.tls.getKafkaConsumers")]
    public static class KafkaConsumers
    {
        /// <summary>
        /// Use this data source to query detailed information of tls kafka consumers
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Volcengine = Pulumi.Volcengine;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Volcengine.Tls.GetKafkaConsumers.Invoke(new()
        ///     {
        ///         Ids = new[]
        ///         {
        ///             "65d67d34-c5b4-4ec8-b3a9-175d33668b45",
        ///             "cfb5c08b-0c7a-44fa-8971-8afc12f1b123",
        ///             "edf051ed-3c46-49ba-9339-bea628fedc15",
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<KafkaConsumersResult> InvokeAsync(KafkaConsumersArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<KafkaConsumersResult>("volcengine:tls/kafkaConsumers:KafkaConsumers", args ?? new KafkaConsumersArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to query detailed information of tls kafka consumers
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Volcengine = Pulumi.Volcengine;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Volcengine.Tls.GetKafkaConsumers.Invoke(new()
        ///     {
        ///         Ids = new[]
        ///         {
        ///             "65d67d34-c5b4-4ec8-b3a9-175d33668b45",
        ///             "cfb5c08b-0c7a-44fa-8971-8afc12f1b123",
        ///             "edf051ed-3c46-49ba-9339-bea628fedc15",
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<KafkaConsumersResult> Invoke(KafkaConsumersInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<KafkaConsumersResult>("volcengine:tls/kafkaConsumers:KafkaConsumers", args ?? new KafkaConsumersInvokeArgs(), options.WithDefaults());
    }


    public sealed class KafkaConsumersArgs : global::Pulumi.InvokeArgs
    {
        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// A list of topic IDs.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        /// <summary>
        /// File name where to save data source results.
        /// </summary>
        [Input("outputFile")]
        public string? OutputFile { get; set; }

        public KafkaConsumersArgs()
        {
        }
        public static new KafkaConsumersArgs Empty => new KafkaConsumersArgs();
    }

    public sealed class KafkaConsumersInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("ids")]
        private InputList<string>? _ids;

        /// <summary>
        /// A list of topic IDs.
        /// </summary>
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        /// <summary>
        /// File name where to save data source results.
        /// </summary>
        [Input("outputFile")]
        public Input<string>? OutputFile { get; set; }

        public KafkaConsumersInvokeArgs()
        {
        }
        public static new KafkaConsumersInvokeArgs Empty => new KafkaConsumersInvokeArgs();
    }


    [OutputType]
    public sealed class KafkaConsumersResult
    {
        /// <summary>
        /// The collection of query.
        /// </summary>
        public readonly ImmutableArray<Outputs.KafkaConsumersDataResult> Datas;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        public readonly string? OutputFile;
        /// <summary>
        /// The total count of query.
        /// </summary>
        public readonly int TotalCount;

        [OutputConstructor]
        private KafkaConsumersResult(
            ImmutableArray<Outputs.KafkaConsumersDataResult> datas,

            string id,

            ImmutableArray<string> ids,

            string? outputFile,

            int totalCount)
        {
            Datas = datas;
            Id = id;
            Ids = ids;
            OutputFile = outputFile;
            TotalCount = totalCount;
        }
    }
}
