// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package escloud_v2

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/internal"
)

// Use this data source to query detailed information of escloud zones v2
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/escloud_v2"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := escloud_v2.GetEscloudZonesV2(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// Deprecated: volcengine.escloud_v2.EscloudZonesV2 has been deprecated in favor of volcengine.escloud_v2.getEscloudZonesV2
func EscloudZonesV2(ctx *pulumi.Context, args *EscloudZonesV2Args, opts ...pulumi.InvokeOption) (*EscloudZonesV2Result, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv EscloudZonesV2Result
	err := ctx.Invoke("volcengine:escloud_v2/escloudZonesV2:EscloudZonesV2", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking EscloudZonesV2.
type EscloudZonesV2Args struct {
	// File name where to save data source results.
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by EscloudZonesV2.
type EscloudZonesV2Result struct {
	// The provider-assigned unique ID for this managed resource.
	Id         string  `pulumi:"id"`
	OutputFile *string `pulumi:"outputFile"`
	// The total count of query.
	TotalCount int `pulumi:"totalCount"`
	// The collection of query.
	Zones []EscloudZonesV2Zone `pulumi:"zones"`
}

func EscloudZonesV2Output(ctx *pulumi.Context, args EscloudZonesV2OutputArgs, opts ...pulumi.InvokeOption) EscloudZonesV2ResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (EscloudZonesV2Result, error) {
			args := v.(EscloudZonesV2Args)
			r, err := EscloudZonesV2(ctx, &args, opts...)
			var s EscloudZonesV2Result
			if r != nil {
				s = *r
			}
			return s, err
		}).(EscloudZonesV2ResultOutput)
}

// A collection of arguments for invoking EscloudZonesV2.
type EscloudZonesV2OutputArgs struct {
	// File name where to save data source results.
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
}

func (EscloudZonesV2OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*EscloudZonesV2Args)(nil)).Elem()
}

// A collection of values returned by EscloudZonesV2.
type EscloudZonesV2ResultOutput struct{ *pulumi.OutputState }

func (EscloudZonesV2ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EscloudZonesV2Result)(nil)).Elem()
}

func (o EscloudZonesV2ResultOutput) ToEscloudZonesV2ResultOutput() EscloudZonesV2ResultOutput {
	return o
}

func (o EscloudZonesV2ResultOutput) ToEscloudZonesV2ResultOutputWithContext(ctx context.Context) EscloudZonesV2ResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o EscloudZonesV2ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v EscloudZonesV2Result) string { return v.Id }).(pulumi.StringOutput)
}

func (o EscloudZonesV2ResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v EscloudZonesV2Result) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

// The total count of query.
func (o EscloudZonesV2ResultOutput) TotalCount() pulumi.IntOutput {
	return o.ApplyT(func(v EscloudZonesV2Result) int { return v.TotalCount }).(pulumi.IntOutput)
}

// The collection of query.
func (o EscloudZonesV2ResultOutput) Zones() EscloudZonesV2ZoneArrayOutput {
	return o.ApplyT(func(v EscloudZonesV2Result) []EscloudZonesV2Zone { return v.Zones }).(EscloudZonesV2ZoneArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(EscloudZonesV2ResultOutput{})
}
