// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Provides a resource to manage rds postgresql data backup
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as volcengine from "@volcengine/pulumi";
 *
 * const example = new volcengine.rds_postgresql.DataBackup("example", {
 *     backupDescription: "tf demo full backup2",
 *     backupMethod: "Physical",
 *     backupScope: "Instance",
 *     backupType: "Full",
 *     instanceId: "postgres-72715e0d9f58",
 * });
 * const example1 = new volcengine.rds_postgresql.DataBackup("example1", {
 *     backupDescription: "tf demo logical backup",
 *     backupMethod: "Logical",
 *     backupScope: "Instance",
 *     instanceId: "postgres-72715e0d9f58",
 * });
 * const example2 = new volcengine.rds_postgresql.DataBackup("example2", {
 *     backupDescription: "tf demo database full backup",
 *     backupMetas: [
 *         {
 *             dbName: "test",
 *         },
 *         {
 *             dbName: "test-1",
 *         },
 *     ],
 *     backupMethod: "Logical",
 *     backupScope: "Database",
 *     instanceId: "postgres-72715e0d9f58",
 * });
 * ```
 *
 * ## Import
 *
 * RdsPostgresqlDataBackup can be imported using the id, e.g.
 *
 * ```sh
 * $ pulumi import volcengine:rds_postgresql/dataBackup:DataBackup default resource_id
 * ```
 */
export class DataBackup extends pulumi.CustomResource {
    /**
     * Get an existing DataBackup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DataBackupState, opts?: pulumi.CustomResourceOptions): DataBackup {
        return new DataBackup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'volcengine:rds_postgresql/dataBackup:DataBackup';

    /**
     * Returns true if the given object is an instance of DataBackup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DataBackup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DataBackup.__pulumiType;
    }

    /**
     * The description of the backup set.
     */
    public readonly backupDescription!: pulumi.Output<string | undefined>;
    /**
     * The id of the backup.
     */
    public /*out*/ readonly backupId!: pulumi.Output<string>;
    /**
     * Specify the database that needs to be backed up. This parameter can only be set when the value of backupScope is Database.
     */
    public readonly backupMetas!: pulumi.Output<outputs.rds_postgresql.DataBackupBackupMeta[] | undefined>;
    /**
     * The method of the backup: Physical, Logical.When the value of backupScope is Database, the value of backupMethod can only be Logical.
     */
    public readonly backupMethod!: pulumi.Output<string | undefined>;
    /**
     * The scope of the backup: Instance, Database.
     */
    public readonly backupScope!: pulumi.Output<string | undefined>;
    /**
     * The backup type of the backup: Full(default), Increment. Do not set this parameter when backupMethod is Logical; otherwise, the creation will fail.
     */
    public readonly backupType!: pulumi.Output<string | undefined>;
    /**
     * The id of the PostgreSQL instance.
     */
    public readonly instanceId!: pulumi.Output<string>;

    /**
     * Create a DataBackup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DataBackupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DataBackupArgs | DataBackupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DataBackupState | undefined;
            resourceInputs["backupDescription"] = state ? state.backupDescription : undefined;
            resourceInputs["backupId"] = state ? state.backupId : undefined;
            resourceInputs["backupMetas"] = state ? state.backupMetas : undefined;
            resourceInputs["backupMethod"] = state ? state.backupMethod : undefined;
            resourceInputs["backupScope"] = state ? state.backupScope : undefined;
            resourceInputs["backupType"] = state ? state.backupType : undefined;
            resourceInputs["instanceId"] = state ? state.instanceId : undefined;
        } else {
            const args = argsOrState as DataBackupArgs | undefined;
            if ((!args || args.instanceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'instanceId'");
            }
            resourceInputs["backupDescription"] = args ? args.backupDescription : undefined;
            resourceInputs["backupMetas"] = args ? args.backupMetas : undefined;
            resourceInputs["backupMethod"] = args ? args.backupMethod : undefined;
            resourceInputs["backupScope"] = args ? args.backupScope : undefined;
            resourceInputs["backupType"] = args ? args.backupType : undefined;
            resourceInputs["instanceId"] = args ? args.instanceId : undefined;
            resourceInputs["backupId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DataBackup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DataBackup resources.
 */
export interface DataBackupState {
    /**
     * The description of the backup set.
     */
    backupDescription?: pulumi.Input<string>;
    /**
     * The id of the backup.
     */
    backupId?: pulumi.Input<string>;
    /**
     * Specify the database that needs to be backed up. This parameter can only be set when the value of backupScope is Database.
     */
    backupMetas?: pulumi.Input<pulumi.Input<inputs.rds_postgresql.DataBackupBackupMeta>[]>;
    /**
     * The method of the backup: Physical, Logical.When the value of backupScope is Database, the value of backupMethod can only be Logical.
     */
    backupMethod?: pulumi.Input<string>;
    /**
     * The scope of the backup: Instance, Database.
     */
    backupScope?: pulumi.Input<string>;
    /**
     * The backup type of the backup: Full(default), Increment. Do not set this parameter when backupMethod is Logical; otherwise, the creation will fail.
     */
    backupType?: pulumi.Input<string>;
    /**
     * The id of the PostgreSQL instance.
     */
    instanceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DataBackup resource.
 */
export interface DataBackupArgs {
    /**
     * The description of the backup set.
     */
    backupDescription?: pulumi.Input<string>;
    /**
     * Specify the database that needs to be backed up. This parameter can only be set when the value of backupScope is Database.
     */
    backupMetas?: pulumi.Input<pulumi.Input<inputs.rds_postgresql.DataBackupBackupMeta>[]>;
    /**
     * The method of the backup: Physical, Logical.When the value of backupScope is Database, the value of backupMethod can only be Logical.
     */
    backupMethod?: pulumi.Input<string>;
    /**
     * The scope of the backup: Instance, Database.
     */
    backupScope?: pulumi.Input<string>;
    /**
     * The backup type of the backup: Full(default), Increment. Do not set this parameter when backupMethod is Logical; otherwise, the creation will fail.
     */
    backupType?: pulumi.Input<string>;
    /**
     * The id of the PostgreSQL instance.
     */
    instanceId: pulumi.Input<string>;
}
