// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Provides a resource to manage rds postgresql restore backup
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as volcengine from "@volcengine/pulumi";
 *
 * const example = new volcengine.rds_postgresql.RestoreBackup("example", {
 *     backupId: "20251214-200431-0698LD",
 *     databases: [{
 *         dbName: "test",
 *         newDbName: "test_restored",
 *     }],
 *     sourceDbInstanceId: "postgres-72715e0d9f58",
 *     targetDbInstanceAccount: "super",
 *     targetDbInstanceId: "postgres-72715e0d9f58",
 * });
 * ```
 *
 * ## Import
 *
 * RdsPostgresqlRestoreBackup can be imported using the id, e.g.
 *
 * ```sh
 * $ pulumi import volcengine:rds_postgresql/restoreBackup:RestoreBackup default resource_id
 * ```
 */
export class RestoreBackup extends pulumi.CustomResource {
    /**
     * Get an existing RestoreBackup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RestoreBackupState, opts?: pulumi.CustomResourceOptions): RestoreBackup {
        return new RestoreBackup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'volcengine:rds_postgresql/restoreBackup:RestoreBackup';

    /**
     * Returns true if the given object is an instance of RestoreBackup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RestoreBackup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RestoreBackup.__pulumiType;
    }

    /**
     * The backup ID used for restore.Only supports restoring data to an existing instance through logical backup.
     */
    public readonly backupId!: pulumi.Output<string>;
    /**
     * Information of the database to be restored.
     */
    public readonly databases!: pulumi.Output<outputs.rds_postgresql.RestoreBackupDatabase[]>;
    /**
     * The ID of the instance to which the backup belongs.
     */
    public readonly sourceDbInstanceId!: pulumi.Output<string>;
    /**
     * The account used as the Owner of the newly restored database in the target instance.
     */
    public readonly targetDbInstanceAccount!: pulumi.Output<string>;
    /**
     * The ID of the target instance for restore.
     */
    public readonly targetDbInstanceId!: pulumi.Output<string>;

    /**
     * Create a RestoreBackup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RestoreBackupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RestoreBackupArgs | RestoreBackupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RestoreBackupState | undefined;
            resourceInputs["backupId"] = state ? state.backupId : undefined;
            resourceInputs["databases"] = state ? state.databases : undefined;
            resourceInputs["sourceDbInstanceId"] = state ? state.sourceDbInstanceId : undefined;
            resourceInputs["targetDbInstanceAccount"] = state ? state.targetDbInstanceAccount : undefined;
            resourceInputs["targetDbInstanceId"] = state ? state.targetDbInstanceId : undefined;
        } else {
            const args = argsOrState as RestoreBackupArgs | undefined;
            if ((!args || args.backupId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'backupId'");
            }
            if ((!args || args.databases === undefined) && !opts.urn) {
                throw new Error("Missing required property 'databases'");
            }
            if ((!args || args.sourceDbInstanceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sourceDbInstanceId'");
            }
            if ((!args || args.targetDbInstanceAccount === undefined) && !opts.urn) {
                throw new Error("Missing required property 'targetDbInstanceAccount'");
            }
            if ((!args || args.targetDbInstanceId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'targetDbInstanceId'");
            }
            resourceInputs["backupId"] = args ? args.backupId : undefined;
            resourceInputs["databases"] = args ? args.databases : undefined;
            resourceInputs["sourceDbInstanceId"] = args ? args.sourceDbInstanceId : undefined;
            resourceInputs["targetDbInstanceAccount"] = args ? args.targetDbInstanceAccount : undefined;
            resourceInputs["targetDbInstanceId"] = args ? args.targetDbInstanceId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RestoreBackup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RestoreBackup resources.
 */
export interface RestoreBackupState {
    /**
     * The backup ID used for restore.Only supports restoring data to an existing instance through logical backup.
     */
    backupId?: pulumi.Input<string>;
    /**
     * Information of the database to be restored.
     */
    databases?: pulumi.Input<pulumi.Input<inputs.rds_postgresql.RestoreBackupDatabase>[]>;
    /**
     * The ID of the instance to which the backup belongs.
     */
    sourceDbInstanceId?: pulumi.Input<string>;
    /**
     * The account used as the Owner of the newly restored database in the target instance.
     */
    targetDbInstanceAccount?: pulumi.Input<string>;
    /**
     * The ID of the target instance for restore.
     */
    targetDbInstanceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RestoreBackup resource.
 */
export interface RestoreBackupArgs {
    /**
     * The backup ID used for restore.Only supports restoring data to an existing instance through logical backup.
     */
    backupId: pulumi.Input<string>;
    /**
     * Information of the database to be restored.
     */
    databases: pulumi.Input<pulumi.Input<inputs.rds_postgresql.RestoreBackupDatabase>[]>;
    /**
     * The ID of the instance to which the backup belongs.
     */
    sourceDbInstanceId: pulumi.Input<string>;
    /**
     * The account used as the Owner of the newly restored database in the target instance.
     */
    targetDbInstanceAccount: pulumi.Input<string>;
    /**
     * The ID of the target instance for restore.
     */
    targetDbInstanceId: pulumi.Input<string>;
}
