// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcengine.Ecs
{
    /// <summary>
    /// Provides a resource to manage iam role attachment
    /// 
    /// ## Import
    /// 
    /// IamRoleAttachment can be imported using the iam_role_name:instance_id, e.g.
    /// 
    /// ```sh
    ///  $ pulumi import volcengine:ecs/iamRoleAttachment:IamRoleAttachment default role_name:instance_id
    /// ```
    /// </summary>
    [VolcengineResourceType("volcengine:ecs/iamRoleAttachment:IamRoleAttachment")]
    public partial class IamRoleAttachment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the iam role.
        /// </summary>
        [Output("iamRoleName")]
        public Output<string> IamRoleName { get; private set; } = null!;

        /// <summary>
        /// The id of the ecs instance.
        /// </summary>
        [Output("instanceId")]
        public Output<string> InstanceId { get; private set; } = null!;


        /// <summary>
        /// Create a IamRoleAttachment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IamRoleAttachment(string name, IamRoleAttachmentArgs args, CustomResourceOptions? options = null)
            : base("volcengine:ecs/iamRoleAttachment:IamRoleAttachment", name, args ?? new IamRoleAttachmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IamRoleAttachment(string name, Input<string> id, IamRoleAttachmentState? state = null, CustomResourceOptions? options = null)
            : base("volcengine:ecs/iamRoleAttachment:IamRoleAttachment", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/volcengine",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IamRoleAttachment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IamRoleAttachment Get(string name, Input<string> id, IamRoleAttachmentState? state = null, CustomResourceOptions? options = null)
        {
            return new IamRoleAttachment(name, id, state, options);
        }
    }

    public sealed class IamRoleAttachmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the iam role.
        /// </summary>
        [Input("iamRoleName", required: true)]
        public Input<string> IamRoleName { get; set; } = null!;

        /// <summary>
        /// The id of the ecs instance.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        public IamRoleAttachmentArgs()
        {
        }
        public static new IamRoleAttachmentArgs Empty => new IamRoleAttachmentArgs();
    }

    public sealed class IamRoleAttachmentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the iam role.
        /// </summary>
        [Input("iamRoleName")]
        public Input<string>? IamRoleName { get; set; }

        /// <summary>
        /// The id of the ecs instance.
        /// </summary>
        [Input("instanceId")]
        public Input<string>? InstanceId { get; set; }

        public IamRoleAttachmentState()
        {
        }
        public static new IamRoleAttachmentState Empty => new IamRoleAttachmentState();
    }
}
