// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Rds_mysql.Inputs
{

    public sealed class AccountTableColumnPrivilegeTablePrivilegeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Table privileges of the account.
        /// </summary>
        [Input("accountPrivilegeDetail")]
        public Input<string>? AccountPrivilegeDetail { get; set; }

        /// <summary>
        /// The name of the table for setting permissions on the account.
        /// </summary>
        [Input("tableName", required: true)]
        public Input<string> TableName { get; set; } = null!;

        public AccountTableColumnPrivilegeTablePrivilegeArgs()
        {
        }
        public static new AccountTableColumnPrivilegeTablePrivilegeArgs Empty => new AccountTableColumnPrivilegeTablePrivilegeArgs();
    }
}
