// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Iam
{
    public static class GetUserGroupAttachments
    {
        /// <summary>
        /// Use this data source to query detailed information of iam user group attachments
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Volcengine = Pulumi.Volcengine;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Volcengine.Iam.GetUserGroupAttachments.Invoke(new()
        ///     {
        ///         UserGroupName = "xRqElT",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetUserGroupAttachmentsResult> InvokeAsync(GetUserGroupAttachmentsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetUserGroupAttachmentsResult>("volcengine:iam/getUserGroupAttachments:getUserGroupAttachments", args ?? new GetUserGroupAttachmentsArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to query detailed information of iam user group attachments
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Volcengine = Pulumi.Volcengine;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @default = Volcengine.Iam.GetUserGroupAttachments.Invoke(new()
        ///     {
        ///         UserGroupName = "xRqElT",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetUserGroupAttachmentsResult> Invoke(GetUserGroupAttachmentsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetUserGroupAttachmentsResult>("volcengine:iam/getUserGroupAttachments:getUserGroupAttachments", args ?? new GetUserGroupAttachmentsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetUserGroupAttachmentsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// File name where to save data source results.
        /// </summary>
        [Input("outputFile")]
        public string? OutputFile { get; set; }

        /// <summary>
        /// The name of user group.
        /// </summary>
        [Input("userGroupName", required: true)]
        public string UserGroupName { get; set; } = null!;

        public GetUserGroupAttachmentsArgs()
        {
        }
        public static new GetUserGroupAttachmentsArgs Empty => new GetUserGroupAttachmentsArgs();
    }

    public sealed class GetUserGroupAttachmentsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// File name where to save data source results.
        /// </summary>
        [Input("outputFile")]
        public Input<string>? OutputFile { get; set; }

        /// <summary>
        /// The name of user group.
        /// </summary>
        [Input("userGroupName", required: true)]
        public Input<string> UserGroupName { get; set; } = null!;

        public GetUserGroupAttachmentsInvokeArgs()
        {
        }
        public static new GetUserGroupAttachmentsInvokeArgs Empty => new GetUserGroupAttachmentsInvokeArgs();
    }


    [OutputType]
    public sealed class GetUserGroupAttachmentsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? OutputFile;
        /// <summary>
        /// The total count of query.
        /// </summary>
        public readonly int TotalCount;
        public readonly string UserGroupName;
        /// <summary>
        /// The collection of user.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetUserGroupAttachmentsUserResult> Users;

        [OutputConstructor]
        private GetUserGroupAttachmentsResult(
            string id,

            string? outputFile,

            int totalCount,

            string userGroupName,

            ImmutableArray<Outputs.GetUserGroupAttachmentsUserResult> users)
        {
            Id = id;
            OutputFile = outputFile;
            TotalCount = totalCount;
            UserGroupName = userGroupName;
            Users = users;
        }
    }
}
