// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Privatelink
{
    public static class GetVpcGatewayEndpoints
    {
        /// <summary>
        /// Use this data source to query detailed information of privatelink vpc gateway endpoints
        /// </summary>
        public static Task<GetVpcGatewayEndpointsResult> InvokeAsync(GetVpcGatewayEndpointsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetVpcGatewayEndpointsResult>("volcengine:privatelink/getVpcGatewayEndpoints:getVpcGatewayEndpoints", args ?? new GetVpcGatewayEndpointsArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to query detailed information of privatelink vpc gateway endpoints
        /// </summary>
        public static Output<GetVpcGatewayEndpointsResult> Invoke(GetVpcGatewayEndpointsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetVpcGatewayEndpointsResult>("volcengine:privatelink/getVpcGatewayEndpoints:getVpcGatewayEndpoints", args ?? new GetVpcGatewayEndpointsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetVpcGatewayEndpointsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the gateway endpoint.
        /// </summary>
        [Input("endpointName")]
        public string? EndpointName { get; set; }

        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// A list of gateway endpoint IDs.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A Name Regex of gateway endpoint.
        /// </summary>
        [Input("nameRegex")]
        public string? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results.
        /// </summary>
        [Input("outputFile")]
        public string? OutputFile { get; set; }

        /// <summary>
        /// The project name of the gateway endpoint.
        /// </summary>
        [Input("projectName")]
        public string? ProjectName { get; set; }

        [Input("tags")]
        private List<Inputs.GetVpcGatewayEndpointsTagArgs>? _tags;

        /// <summary>
        /// Tags.
        /// </summary>
        public List<Inputs.GetVpcGatewayEndpointsTagArgs> Tags
        {
            get => _tags ?? (_tags = new List<Inputs.GetVpcGatewayEndpointsTagArgs>());
            set => _tags = value;
        }

        /// <summary>
        /// The id of the vpc.
        /// </summary>
        [Input("vpcId")]
        public string? VpcId { get; set; }

        public GetVpcGatewayEndpointsArgs()
        {
        }
        public static new GetVpcGatewayEndpointsArgs Empty => new GetVpcGatewayEndpointsArgs();
    }

    public sealed class GetVpcGatewayEndpointsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the gateway endpoint.
        /// </summary>
        [Input("endpointName")]
        public Input<string>? EndpointName { get; set; }

        [Input("ids")]
        private InputList<string>? _ids;

        /// <summary>
        /// A list of gateway endpoint IDs.
        /// </summary>
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A Name Regex of gateway endpoint.
        /// </summary>
        [Input("nameRegex")]
        public Input<string>? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results.
        /// </summary>
        [Input("outputFile")]
        public Input<string>? OutputFile { get; set; }

        /// <summary>
        /// The project name of the gateway endpoint.
        /// </summary>
        [Input("projectName")]
        public Input<string>? ProjectName { get; set; }

        [Input("tags")]
        private InputList<Inputs.GetVpcGatewayEndpointsTagInputArgs>? _tags;

        /// <summary>
        /// Tags.
        /// </summary>
        public InputList<Inputs.GetVpcGatewayEndpointsTagInputArgs> Tags
        {
            get => _tags ?? (_tags = new InputList<Inputs.GetVpcGatewayEndpointsTagInputArgs>());
            set => _tags = value;
        }

        /// <summary>
        /// The id of the vpc.
        /// </summary>
        [Input("vpcId")]
        public Input<string>? VpcId { get; set; }

        public GetVpcGatewayEndpointsInvokeArgs()
        {
        }
        public static new GetVpcGatewayEndpointsInvokeArgs Empty => new GetVpcGatewayEndpointsInvokeArgs();
    }


    [OutputType]
    public sealed class GetVpcGatewayEndpointsResult
    {
        /// <summary>
        /// The name of the gateway endpoint.
        /// </summary>
        public readonly string? EndpointName;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        public readonly string? NameRegex;
        public readonly string? OutputFile;
        /// <summary>
        /// The project name of the gateway endpoint.
        /// </summary>
        public readonly string? ProjectName;
        /// <summary>
        /// Tags.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpcGatewayEndpointsTagResult> Tags;
        /// <summary>
        /// The total count of query.
        /// </summary>
        public readonly int TotalCount;
        /// <summary>
        /// The collection of query.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpcGatewayEndpointsVpcGatewayEndpointResult> VpcGatewayEndpoints;
        /// <summary>
        /// The id of the vpc.
        /// </summary>
        public readonly string? VpcId;

        [OutputConstructor]
        private GetVpcGatewayEndpointsResult(
            string? endpointName,

            string id,

            ImmutableArray<string> ids,

            string? nameRegex,

            string? outputFile,

            string? projectName,

            ImmutableArray<Outputs.GetVpcGatewayEndpointsTagResult> tags,

            int totalCount,

            ImmutableArray<Outputs.GetVpcGatewayEndpointsVpcGatewayEndpointResult> vpcGatewayEndpoints,

            string? vpcId)
        {
            EndpointName = endpointName;
            Id = id;
            Ids = ids;
            NameRegex = nameRegex;
            OutputFile = outputFile;
            ProjectName = projectName;
            Tags = tags;
            TotalCount = totalCount;
            VpcGatewayEndpoints = vpcGatewayEndpoints;
            VpcId = vpcId;
        }
    }
}
