// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Privatelink
{
    /// <summary>
    /// Provides a resource to manage privatelink vpc endpoint connection
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Volcengine = Pulumi.Volcengine;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var foo = new Volcengine.Privatelink.VpcEndpointConnection("foo", new Volcengine.Privatelink.VpcEndpointConnectionArgs
    ///         {
    ///             EndpointId = "ep-3rel74u229dz45zsk2i6l69qa",
    ///             ServiceId = "epsvc-2byz5mykk9y4g2dx0efs4aqz3",
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// 
    /// ## Import
    /// 
    /// PrivateLink Vpc Endpoint Connection Service can be imported using the endpoint id and service id, e.g.
    /// 
    /// ```sh
    ///  $ pulumi import volcengine:privatelink/vpcEndpointConnection:VpcEndpointConnection default ep-3rel74u229dz45zsk2i6l69qa:epsvc-2byz5mykk9y4g2dx0efs4aqz3
    /// ```
    /// </summary>
    [VolcengineResourceType("volcengine:privatelink/vpcEndpointConnection:VpcEndpointConnection")]
    public partial class VpcEndpointConnection : Pulumi.CustomResource
    {
        /// <summary>
        /// The status of the connection.
        /// </summary>
        [Output("connectionStatus")]
        public Output<string> ConnectionStatus { get; private set; } = null!;

        /// <summary>
        /// The create time of the connection.
        /// </summary>
        [Output("creationTime")]
        public Output<string> CreationTime { get; private set; } = null!;

        /// <summary>
        /// The id of the endpoint.
        /// </summary>
        [Output("endpointId")]
        public Output<string> EndpointId { get; private set; } = null!;

        /// <summary>
        /// The account id of the vpc endpoint.
        /// </summary>
        [Output("endpointOwnerAccountId")]
        public Output<string> EndpointOwnerAccountId { get; private set; } = null!;

        /// <summary>
        /// The vpc id of the vpc endpoint.
        /// </summary>
        [Output("endpointVpcId")]
        public Output<string> EndpointVpcId { get; private set; } = null!;

        /// <summary>
        /// The id of the security group.
        /// </summary>
        [Output("serviceId")]
        public Output<string> ServiceId { get; private set; } = null!;

        /// <summary>
        /// The update time of the connection.
        /// </summary>
        [Output("updateTime")]
        public Output<string> UpdateTime { get; private set; } = null!;

        /// <summary>
        /// The available zones.
        /// </summary>
        [Output("zones")]
        public Output<ImmutableArray<Outputs.VpcEndpointConnectionZone>> Zones { get; private set; } = null!;


        /// <summary>
        /// Create a VpcEndpointConnection resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VpcEndpointConnection(string name, VpcEndpointConnectionArgs args, CustomResourceOptions? options = null)
            : base("volcengine:privatelink/vpcEndpointConnection:VpcEndpointConnection", name, args ?? new VpcEndpointConnectionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VpcEndpointConnection(string name, Input<string> id, VpcEndpointConnectionState? state = null, CustomResourceOptions? options = null)
            : base("volcengine:privatelink/vpcEndpointConnection:VpcEndpointConnection", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VpcEndpointConnection resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VpcEndpointConnection Get(string name, Input<string> id, VpcEndpointConnectionState? state = null, CustomResourceOptions? options = null)
        {
            return new VpcEndpointConnection(name, id, state, options);
        }
    }

    public sealed class VpcEndpointConnectionArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The id of the endpoint.
        /// </summary>
        [Input("endpointId", required: true)]
        public Input<string> EndpointId { get; set; } = null!;

        /// <summary>
        /// The id of the security group.
        /// </summary>
        [Input("serviceId", required: true)]
        public Input<string> ServiceId { get; set; } = null!;

        public VpcEndpointConnectionArgs()
        {
        }
    }

    public sealed class VpcEndpointConnectionState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The status of the connection.
        /// </summary>
        [Input("connectionStatus")]
        public Input<string>? ConnectionStatus { get; set; }

        /// <summary>
        /// The create time of the connection.
        /// </summary>
        [Input("creationTime")]
        public Input<string>? CreationTime { get; set; }

        /// <summary>
        /// The id of the endpoint.
        /// </summary>
        [Input("endpointId")]
        public Input<string>? EndpointId { get; set; }

        /// <summary>
        /// The account id of the vpc endpoint.
        /// </summary>
        [Input("endpointOwnerAccountId")]
        public Input<string>? EndpointOwnerAccountId { get; set; }

        /// <summary>
        /// The vpc id of the vpc endpoint.
        /// </summary>
        [Input("endpointVpcId")]
        public Input<string>? EndpointVpcId { get; set; }

        /// <summary>
        /// The id of the security group.
        /// </summary>
        [Input("serviceId")]
        public Input<string>? ServiceId { get; set; }

        /// <summary>
        /// The update time of the connection.
        /// </summary>
        [Input("updateTime")]
        public Input<string>? UpdateTime { get; set; }

        [Input("zones")]
        private InputList<Inputs.VpcEndpointConnectionZoneGetArgs>? _zones;

        /// <summary>
        /// The available zones.
        /// </summary>
        public InputList<Inputs.VpcEndpointConnectionZoneGetArgs> Zones
        {
            get => _zones ?? (_zones = new InputList<Inputs.VpcEndpointConnectionZoneGetArgs>());
            set => _zones = value;
        }

        public VpcEndpointConnectionState()
        {
        }
    }
}
