// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package iam

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/internal"
)

// Use this data source to query detailed information of iam allowed ip addresses
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/volcengine/pulumi-volcengine/sdk/go/volcengine/iam"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := iam.GetAllowedIpAddresses(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// Deprecated: volcengine.iam.AllowedIpAddresses has been deprecated in favor of volcengine.iam.getAllowedIpAddresses
func AllowedIpAddresses(ctx *pulumi.Context, args *AllowedIpAddressesArgs, opts ...pulumi.InvokeOption) (*AllowedIpAddressesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv AllowedIpAddressesResult
	err := ctx.Invoke("volcengine:iam/allowedIpAddresses:AllowedIpAddresses", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking AllowedIpAddresses.
type AllowedIpAddressesArgs struct {
	// File name where to save data source results.
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by AllowedIpAddresses.
type AllowedIpAddressesResult struct {
	// The collection of query.
	AllowedIpAddresses []AllowedIpAddressesAllowedIpAddress `pulumi:"allowedIpAddresses"`
	// The provider-assigned unique ID for this managed resource.
	Id         string  `pulumi:"id"`
	OutputFile *string `pulumi:"outputFile"`
}

func AllowedIpAddressesOutput(ctx *pulumi.Context, args AllowedIpAddressesOutputArgs, opts ...pulumi.InvokeOption) AllowedIpAddressesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (AllowedIpAddressesResult, error) {
			args := v.(AllowedIpAddressesArgs)
			r, err := AllowedIpAddresses(ctx, &args, opts...)
			var s AllowedIpAddressesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(AllowedIpAddressesResultOutput)
}

// A collection of arguments for invoking AllowedIpAddresses.
type AllowedIpAddressesOutputArgs struct {
	// File name where to save data source results.
	OutputFile pulumi.StringPtrInput `pulumi:"outputFile"`
}

func (AllowedIpAddressesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AllowedIpAddressesArgs)(nil)).Elem()
}

// A collection of values returned by AllowedIpAddresses.
type AllowedIpAddressesResultOutput struct{ *pulumi.OutputState }

func (AllowedIpAddressesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AllowedIpAddressesResult)(nil)).Elem()
}

func (o AllowedIpAddressesResultOutput) ToAllowedIpAddressesResultOutput() AllowedIpAddressesResultOutput {
	return o
}

func (o AllowedIpAddressesResultOutput) ToAllowedIpAddressesResultOutputWithContext(ctx context.Context) AllowedIpAddressesResultOutput {
	return o
}

// The collection of query.
func (o AllowedIpAddressesResultOutput) AllowedIpAddresses() AllowedIpAddressesAllowedIpAddressArrayOutput {
	return o.ApplyT(func(v AllowedIpAddressesResult) []AllowedIpAddressesAllowedIpAddress { return v.AllowedIpAddresses }).(AllowedIpAddressesAllowedIpAddressArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o AllowedIpAddressesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v AllowedIpAddressesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o AllowedIpAddressesResultOutput) OutputFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AllowedIpAddressesResult) *string { return v.OutputFile }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(AllowedIpAddressesResultOutput{})
}
