// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Use this data source to query detailed information of tls trace instances
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as volcengine from "@pulumi/volcengine";
 *
 * const byName = volcengine.tls.getTraceInstances({
 *     projectId: "bdb87e4d-7dad-4b96-ac43-e1b09e9dc8ac",
 *     traceInstanceName: "tf-trace-instance-nn",
 * });
 * ```
 */
export function getTraceInstances(args?: GetTraceInstancesArgs, opts?: pulumi.InvokeOptions): Promise<GetTraceInstancesResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("volcengine:tls/getTraceInstances:getTraceInstances", {
        "csAccountChannel": args.csAccountChannel,
        "iamProjectName": args.iamProjectName,
        "outputFile": args.outputFile,
        "projectId": args.projectId,
        "projectName": args.projectName,
        "status": args.status,
        "traceInstanceId": args.traceInstanceId,
        "traceInstanceName": args.traceInstanceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getTraceInstances.
 */
export interface GetTraceInstancesArgs {
    /**
     * CS account channel identifier.
     */
    csAccountChannel?: string;
    /**
     * The IAM project name.
     */
    iamProjectName?: string;
    /**
     * File name where to save data source results.
     */
    outputFile?: string;
    /**
     * The ID of the project.
     */
    projectId?: string;
    /**
     * The name of the project.
     */
    projectName?: string;
    /**
     * The status of the trace instance.
     */
    status?: string;
    /**
     * The ID of the trace instance.
     */
    traceInstanceId?: string;
    /**
     * The name of the trace instance.
     */
    traceInstanceName?: string;
}

/**
 * A collection of values returned by getTraceInstances.
 */
export interface GetTraceInstancesResult {
    /**
     * CS account channel identifier.
     */
    readonly csAccountChannel?: string;
    readonly iamProjectName?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly outputFile?: string;
    /**
     * The ID of the project.
     */
    readonly projectId?: string;
    /**
     * The name of the project.
     */
    readonly projectName?: string;
    readonly status?: string;
    /**
     * The total count of trace instances.
     */
    readonly totalCount: number;
    /**
     * The ID of the trace instance.
     */
    readonly traceInstanceId?: string;
    /**
     * The name of the trace instance.
     */
    readonly traceInstanceName?: string;
    /**
     * The list of trace instances.
     */
    readonly traceInstances: outputs.tls.GetTraceInstancesTraceInstance[];
}
/**
 * Use this data source to query detailed information of tls trace instances
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as volcengine from "@pulumi/volcengine";
 *
 * const byName = volcengine.tls.getTraceInstances({
 *     projectId: "bdb87e4d-7dad-4b96-ac43-e1b09e9dc8ac",
 *     traceInstanceName: "tf-trace-instance-nn",
 * });
 * ```
 */
export function getTraceInstancesOutput(args?: GetTraceInstancesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetTraceInstancesResult> {
    return pulumi.output(args).apply((a: any) => getTraceInstances(a, opts))
}

/**
 * A collection of arguments for invoking getTraceInstances.
 */
export interface GetTraceInstancesOutputArgs {
    /**
     * CS account channel identifier.
     */
    csAccountChannel?: pulumi.Input<string>;
    /**
     * The IAM project name.
     */
    iamProjectName?: pulumi.Input<string>;
    /**
     * File name where to save data source results.
     */
    outputFile?: pulumi.Input<string>;
    /**
     * The ID of the project.
     */
    projectId?: pulumi.Input<string>;
    /**
     * The name of the project.
     */
    projectName?: pulumi.Input<string>;
    /**
     * The status of the trace instance.
     */
    status?: pulumi.Input<string>;
    /**
     * The ID of the trace instance.
     */
    traceInstanceId?: pulumi.Input<string>;
    /**
     * The name of the trace instance.
     */
    traceInstanceName?: pulumi.Input<string>;
}
