// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Rds_mysql.Outputs
{

    [OutputType]
    public sealed class GetAllowlistsAllowListSecurityGroupBindInfoResult
    {
        /// <summary>
        /// The schema for the associated security group.
        /// IngressDirectionIp: Incoming Direction IP.
        /// AssociateEcsIp: Associate ECSIP.
        /// explain: In the CreateAllowList interface, SecurityGroupBindInfoObject BindMode and SecurityGroupId fields are required.
        /// </summary>
        public readonly string BindMode;
        /// <summary>
        /// The ip list of the security group.
        /// </summary>
        public readonly ImmutableArray<string> IpLists;
        /// <summary>
        /// The security group id of the allow list.
        /// </summary>
        public readonly string SecurityGroupId;
        /// <summary>
        /// The name of the security group.
        /// </summary>
        public readonly string SecurityGroupName;

        [OutputConstructor]
        private GetAllowlistsAllowListSecurityGroupBindInfoResult(
            string bindMode,

            ImmutableArray<string> ipLists,

            string securityGroupId,

            string securityGroupName)
        {
            BindMode = bindMode;
            IpLists = ipLists;
            SecurityGroupId = securityGroupId;
            SecurityGroupName = securityGroupName;
        }
    }
}
