// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Waf
{
    [Obsolete(@"volcengine.waf.ServiceCertificates has been deprecated in favor of volcengine.waf.getServiceCertificates")]
    public static class ServiceCertificates
    {
        /// <summary>
        /// Use this data source to query detailed information of waf service certificates
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Volcengine = Pulumi.Volcengine;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var foo = Volcengine.Waf.GetServiceCertificates.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<ServiceCertificatesResult> InvokeAsync(ServiceCertificatesArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<ServiceCertificatesResult>("volcengine:waf/serviceCertificates:ServiceCertificates", args ?? new ServiceCertificatesArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to query detailed information of waf service certificates
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Volcengine = Pulumi.Volcengine;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var foo = Volcengine.Waf.GetServiceCertificates.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<ServiceCertificatesResult> Invoke(ServiceCertificatesInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<ServiceCertificatesResult>("volcengine:waf/serviceCertificates:ServiceCertificates", args ?? new ServiceCertificatesInvokeArgs(), options.WithDefaults());
    }


    public sealed class ServiceCertificatesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A Name Regex of Resource.
        /// </summary>
        [Input("nameRegex")]
        public string? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results.
        /// </summary>
        [Input("outputFile")]
        public string? OutputFile { get; set; }

        public ServiceCertificatesArgs()
        {
        }
        public static new ServiceCertificatesArgs Empty => new ServiceCertificatesArgs();
    }

    public sealed class ServiceCertificatesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A Name Regex of Resource.
        /// </summary>
        [Input("nameRegex")]
        public Input<string>? NameRegex { get; set; }

        /// <summary>
        /// File name where to save data source results.
        /// </summary>
        [Input("outputFile")]
        public Input<string>? OutputFile { get; set; }

        public ServiceCertificatesInvokeArgs()
        {
        }
        public static new ServiceCertificatesInvokeArgs Empty => new ServiceCertificatesInvokeArgs();
    }


    [OutputType]
    public sealed class ServiceCertificatesResult
    {
        /// <summary>
        /// The Information of the certificate.
        /// </summary>
        public readonly ImmutableArray<Outputs.ServiceCertificatesDataResult> Datas;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? NameRegex;
        public readonly string? OutputFile;
        /// <summary>
        /// The total count of query.
        /// </summary>
        public readonly int TotalCount;

        [OutputConstructor]
        private ServiceCertificatesResult(
            ImmutableArray<Outputs.ServiceCertificatesDataResult> datas,

            string id,

            string? nameRegex,

            string? outputFile,

            int totalCount)
        {
            Datas = datas;
            Id = id;
            NameRegex = nameRegex;
            OutputFile = outputFile;
            TotalCount = totalCount;
        }
    }
}
