// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Cloud_monitor.Outputs
{

    [OutputType]
    public sealed class EventRuleEffectiveTime
    {
        /// <summary>
        /// End time for rule activation.
        /// </summary>
        public readonly string EndTime;
        /// <summary>
        /// Start time for rule activation.
        /// </summary>
        public readonly string StartTime;

        [OutputConstructor]
        private EventRuleEffectiveTime(
            string endTime,

            string startTime)
        {
            EndTime = endTime;
            StartTime = startTime;
        }
    }
}
