// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.PulumiPackage.Volcengine.Clb.Outputs
{

    [OutputType]
    public sealed class ZonesMasterZoneResult
    {
        /// <summary>
        /// The slave zones list.
        /// </summary>
        public readonly ImmutableArray<Outputs.ZonesMasterZoneSlaveZoneResult> SlaveZones;
        /// <summary>
        /// The master zone id.
        /// </summary>
        public readonly string ZoneId;

        [OutputConstructor]
        private ZonesMasterZoneResult(
            ImmutableArray<Outputs.ZonesMasterZoneSlaveZoneResult> slaveZones,

            string zoneId)
        {
            SlaveZones = slaveZones;
            ZoneId = zoneId;
        }
    }
}
