// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.PulumiPackage.Volcengine.Vke.Outputs
{

    [OutputType]
    public sealed class DefaultNodePoolInstance
    {
        /// <summary>
        /// The flag of additional container storage enable, the value is `true` or `false`..Default is `false`.
        /// </summary>
        public readonly bool? AdditionalContainerStorageEnabled;
        /// <summary>
        /// The container storage path.When additional_container_storage_enabled is `false` will ignore.
        /// </summary>
        public readonly string? ContainerStoragePath;
        /// <summary>
        /// ID of the resource.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The Image Id to the ECS Instance.
        /// </summary>
        public readonly string? ImageId;
        /// <summary>
        /// The instance id.
        /// </summary>
        public readonly string InstanceId;
        /// <summary>
        /// The flag of keep instance name, the value is `true` or `false`.Default is `false`.
        /// </summary>
        public readonly bool? KeepInstanceName;
        public readonly string? Phase;

        [OutputConstructor]
        private DefaultNodePoolInstance(
            bool? additionalContainerStorageEnabled,

            string? containerStoragePath,

            string? id,

            string? imageId,

            string instanceId,

            bool? keepInstanceName,

            string? phase)
        {
            AdditionalContainerStorageEnabled = additionalContainerStorageEnabled;
            ContainerStoragePath = containerStoragePath;
            Id = id;
            ImageId = imageId;
            InstanceId = instanceId;
            KeepInstanceName = keepInstanceName;
            Phase = phase;
        }
    }
}
