// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Tos.Inputs
{

    public sealed class BucketWebsiteRoutingRuleRedirectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The host name to redirect to.
        /// </summary>
        [Input("hostName")]
        public Input<string>? HostName { get; set; }

        /// <summary>
        /// The HTTP redirect code to use, e.g., 301, 302.
        /// </summary>
        [Input("httpRedirectCode")]
        public Input<int>? HttpRedirectCode { get; set; }

        /// <summary>
        /// The protocol to use for the redirect. Valid values: http, https.
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        /// <summary>
        /// The key prefix to replace the original key prefix with.
        /// </summary>
        [Input("replaceKeyPrefixWith")]
        public Input<string>? ReplaceKeyPrefixWith { get; set; }

        /// <summary>
        /// The key to replace the original key with.
        /// </summary>
        [Input("replaceKeyWith")]
        public Input<string>? ReplaceKeyWith { get; set; }

        public BucketWebsiteRoutingRuleRedirectArgs()
        {
        }
        public static new BucketWebsiteRoutingRuleRedirectArgs Empty => new BucketWebsiteRoutingRuleRedirectArgs();
    }
}
