// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Use this data source to query detailed information of veecp edge node pools
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as volcengine from "@pulumi/volcengine";
 * import * as volcengine from "@volcengine/pulumi";
 *
 * const fooZones = volcengine.ecs.getZones({});
 * const fooVpc = new volcengine.vpc.Vpc("fooVpc", {
 *     vpcName: "acc-test-project1",
 *     cidrBlock: "172.16.0.0/16",
 * });
 * const fooSubnet = new volcengine.vpc.Subnet("fooSubnet", {
 *     subnetName: "acc-subnet-test-2",
 *     cidrBlock: "172.16.0.0/24",
 *     zoneId: fooZones.then(fooZones => fooZones.zones?.[0]?.id),
 *     vpcId: fooVpc.id,
 * });
 * const fooSecurityGroup = new volcengine.vpc.SecurityGroup("fooSecurityGroup", {
 *     vpcId: fooVpc.id,
 *     securityGroupName: "acc-test-security-group2",
 * });
 * const fooCluster = new volcengine.veecp.Cluster("fooCluster", {
 *     description: "created by terraform",
 *     deleteProtectionEnabled: false,
 *     profile: "Edge",
 *     clusterConfig: {
 *         subnetIds: [fooSubnet.id],
 *         apiServerPublicAccessEnabled: true,
 *         apiServerPublicAccessConfig: {
 *             publicAccessNetworkConfig: {
 *                 billingType: "PostPaidByBandwidth",
 *                 bandwidth: 1,
 *             },
 *         },
 *         resourcePublicAccessDefaultEnabled: true,
 *     },
 *     podsConfig: {
 *         podNetworkMode: "Flannel",
 *         flannelConfig: {
 *             podCidrs: ["172.22.224.0/20"],
 *             maxPodsPerNode: 64,
 *         },
 *     },
 *     servicesConfig: {
 *         serviceCidrsv4s: ["172.30.0.0/18"],
 *     },
 * });
 * const fooEdgeNodePool = new volcengine.veecp.EdgeNodePool("fooEdgeNodePool", {clusterId: fooCluster.id});
 * const fooEdgeNodePools = volcengine.veecp.getEdgeNodePoolsOutput({
 *     clusterIds: [fooCluster.id],
 *     ids: [fooEdgeNodePool.id],
 * });
 * ```
 */
export function getEdgeNodePools(args?: GetEdgeNodePoolsArgs, opts?: pulumi.InvokeOptions): Promise<GetEdgeNodePoolsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("volcengine:veecp/getEdgeNodePools:getEdgeNodePools", {
        "addByAuto": args.addByAuto,
        "addByList": args.addByList,
        "addByScript": args.addByScript,
        "autoScalingEnabled": args.autoScalingEnabled,
        "clusterIds": args.clusterIds,
        "createClientToken": args.createClientToken,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "nodePoolTypes": args.nodePoolTypes,
        "outputFile": args.outputFile,
        "statuses": args.statuses,
        "updateClientToken": args.updateClientToken,
    }, opts);
}

/**
 * A collection of arguments for invoking getEdgeNodePools.
 */
export interface GetEdgeNodePoolsArgs {
    /**
     * Managed by auto.
     */
    addByAuto?: boolean;
    /**
     * Managed by list.
     */
    addByList?: boolean;
    /**
     * Managed by script.
     */
    addByScript?: boolean;
    /**
     * Is enabled of AutoScaling.
     */
    autoScalingEnabled?: boolean;
    /**
     * The ClusterIds of NodePool IDs.
     */
    clusterIds?: string[];
    /**
     * The ClientToken when successfully created.
     */
    createClientToken?: string;
    /**
     * A list of IDs.
     */
    ids?: string[];
    /**
     * A Name Regex of Resource.
     */
    nameRegex?: string;
    /**
     * The NodePoolTypes of NodePool.
     */
    nodePoolTypes?: string[];
    /**
     * File name where to save data source results.
     */
    outputFile?: string;
    /**
     * The Status of NodePool.
     */
    statuses?: inputs.veecp.GetEdgeNodePoolsStatus[];
    /**
     * The ClientToken when last update was successful.
     */
    updateClientToken?: string;
}

/**
 * A collection of values returned by getEdgeNodePools.
 */
export interface GetEdgeNodePoolsResult {
    readonly addByAuto?: boolean;
    readonly addByList?: boolean;
    readonly addByScript?: boolean;
    readonly autoScalingEnabled?: boolean;
    readonly clusterIds?: string[];
    /**
     * The ClientToken when successfully created.
     */
    readonly createClientToken?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids?: string[];
    readonly nameRegex?: string;
    readonly nodePoolTypes?: string[];
    /**
     * The collection of query.
     */
    readonly nodePools: outputs.veecp.GetEdgeNodePoolsNodePool[];
    readonly outputFile?: string;
    readonly statuses?: outputs.veecp.GetEdgeNodePoolsStatus[];
    /**
     * The total count of query.
     */
    readonly totalCount: number;
    /**
     * The ClientToken when last update was successful.
     */
    readonly updateClientToken?: string;
}
/**
 * Use this data source to query detailed information of veecp edge node pools
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as volcengine from "@pulumi/volcengine";
 * import * as volcengine from "@volcengine/pulumi";
 *
 * const fooZones = volcengine.ecs.getZones({});
 * const fooVpc = new volcengine.vpc.Vpc("fooVpc", {
 *     vpcName: "acc-test-project1",
 *     cidrBlock: "172.16.0.0/16",
 * });
 * const fooSubnet = new volcengine.vpc.Subnet("fooSubnet", {
 *     subnetName: "acc-subnet-test-2",
 *     cidrBlock: "172.16.0.0/24",
 *     zoneId: fooZones.then(fooZones => fooZones.zones?.[0]?.id),
 *     vpcId: fooVpc.id,
 * });
 * const fooSecurityGroup = new volcengine.vpc.SecurityGroup("fooSecurityGroup", {
 *     vpcId: fooVpc.id,
 *     securityGroupName: "acc-test-security-group2",
 * });
 * const fooCluster = new volcengine.veecp.Cluster("fooCluster", {
 *     description: "created by terraform",
 *     deleteProtectionEnabled: false,
 *     profile: "Edge",
 *     clusterConfig: {
 *         subnetIds: [fooSubnet.id],
 *         apiServerPublicAccessEnabled: true,
 *         apiServerPublicAccessConfig: {
 *             publicAccessNetworkConfig: {
 *                 billingType: "PostPaidByBandwidth",
 *                 bandwidth: 1,
 *             },
 *         },
 *         resourcePublicAccessDefaultEnabled: true,
 *     },
 *     podsConfig: {
 *         podNetworkMode: "Flannel",
 *         flannelConfig: {
 *             podCidrs: ["172.22.224.0/20"],
 *             maxPodsPerNode: 64,
 *         },
 *     },
 *     servicesConfig: {
 *         serviceCidrsv4s: ["172.30.0.0/18"],
 *     },
 * });
 * const fooEdgeNodePool = new volcengine.veecp.EdgeNodePool("fooEdgeNodePool", {clusterId: fooCluster.id});
 * const fooEdgeNodePools = volcengine.veecp.getEdgeNodePoolsOutput({
 *     clusterIds: [fooCluster.id],
 *     ids: [fooEdgeNodePool.id],
 * });
 * ```
 */
export function getEdgeNodePoolsOutput(args?: GetEdgeNodePoolsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetEdgeNodePoolsResult> {
    return pulumi.output(args).apply((a: any) => getEdgeNodePools(a, opts))
}

/**
 * A collection of arguments for invoking getEdgeNodePools.
 */
export interface GetEdgeNodePoolsOutputArgs {
    /**
     * Managed by auto.
     */
    addByAuto?: pulumi.Input<boolean>;
    /**
     * Managed by list.
     */
    addByList?: pulumi.Input<boolean>;
    /**
     * Managed by script.
     */
    addByScript?: pulumi.Input<boolean>;
    /**
     * Is enabled of AutoScaling.
     */
    autoScalingEnabled?: pulumi.Input<boolean>;
    /**
     * The ClusterIds of NodePool IDs.
     */
    clusterIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ClientToken when successfully created.
     */
    createClientToken?: pulumi.Input<string>;
    /**
     * A list of IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A Name Regex of Resource.
     */
    nameRegex?: pulumi.Input<string>;
    /**
     * The NodePoolTypes of NodePool.
     */
    nodePoolTypes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * File name where to save data source results.
     */
    outputFile?: pulumi.Input<string>;
    /**
     * The Status of NodePool.
     */
    statuses?: pulumi.Input<pulumi.Input<inputs.veecp.GetEdgeNodePoolsStatusArgs>[]>;
    /**
     * The ClientToken when last update was successful.
     */
    updateClientToken?: pulumi.Input<string>;
}
