// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Volcengine.Pulumi.Volcengine.Transit_router.Outputs
{

    [OutputType]
    public sealed class PeerAttachmentsTransitRouterAttachmentResult
    {
        /// <summary>
        /// The bandwidth of the transit router peer attachment.
        /// </summary>
        public readonly int Bandwidth;
        /// <summary>
        /// The creation time of the transit router peer attachment.
        /// </summary>
        public readonly string CreationTime;
        /// <summary>
        /// The description of the transit router peer attachment.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The id of the transit router peer attachment.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The id of peer transit router.
        /// </summary>
        public readonly string PeerTransitRouterId;
        /// <summary>
        /// The region id of peer transit router.
        /// </summary>
        public readonly string PeerTransitRouterRegionId;
        /// <summary>
        /// The status of the transit router peer attachment.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// The id of the transit router peer attachment.
        /// </summary>
        public readonly string TransitRouterAttachmentId;
        /// <summary>
        /// The name of transit router peer attachment.
        /// </summary>
        public readonly string TransitRouterAttachmentName;
        /// <summary>
        /// The bandwidth package id of the transit router peer attachment.
        /// </summary>
        public readonly string TransitRouterBandwidthPackageId;
        /// <summary>
        /// The id of local transit router.
        /// </summary>
        public readonly string TransitRouterId;
        /// <summary>
        /// The route table id of the transit router peer attachment.
        /// </summary>
        public readonly string TransitRouterRouteTableId;
        /// <summary>
        /// The update time of the transit router peer attachment.
        /// </summary>
        public readonly string UpdateTime;

        [OutputConstructor]
        private PeerAttachmentsTransitRouterAttachmentResult(
            int bandwidth,

            string creationTime,

            string description,

            string id,

            string peerTransitRouterId,

            string peerTransitRouterRegionId,

            string status,

            string transitRouterAttachmentId,

            string transitRouterAttachmentName,

            string transitRouterBandwidthPackageId,

            string transitRouterId,

            string transitRouterRouteTableId,

            string updateTime)
        {
            Bandwidth = bandwidth;
            CreationTime = creationTime;
            Description = description;
            Id = id;
            PeerTransitRouterId = peerTransitRouterId;
            PeerTransitRouterRegionId = peerTransitRouterRegionId;
            Status = status;
            TransitRouterAttachmentId = transitRouterAttachmentId;
            TransitRouterAttachmentName = transitRouterAttachmentName;
            TransitRouterBandwidthPackageId = transitRouterBandwidthPackageId;
            TransitRouterId = transitRouterId;
            TransitRouterRouteTableId = transitRouterRouteTableId;
            UpdateTime = updateTime;
        }
    }
}
