// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Tls.Outputs
{

    [OutputType]
    public sealed class DescribeTracesTraceSpanLinkResult
    {
        /// <summary>
        /// Resource attributes.
        /// </summary>
        public readonly ImmutableArray<Outputs.DescribeTracesTraceSpanLinkAttributeResult> Attributes;
        /// <summary>
        /// Span ID.
        /// </summary>
        public readonly string SpanId;
        /// <summary>
        /// Trace ID.
        /// </summary>
        public readonly string TraceId;
        /// <summary>
        /// Trace state.
        /// </summary>
        public readonly string TraceState;

        [OutputConstructor]
        private DescribeTracesTraceSpanLinkResult(
            ImmutableArray<Outputs.DescribeTracesTraceSpanLinkAttributeResult> attributes,

            string spanId,

            string traceId,

            string traceState)
        {
            Attributes = attributes;
            SpanId = spanId;
            TraceId = traceId;
            TraceState = traceState;
        }
    }
}
