// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Tls.Outputs
{

    [OutputType]
    public sealed class DescribeTracesTraceSpanEventResult
    {
        /// <summary>
        /// Resource attributes.
        /// </summary>
        public readonly ImmutableArray<Outputs.DescribeTracesTraceSpanEventAttributeResult> Attributes;
        /// <summary>
        /// Span name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Event timestamp.
        /// </summary>
        public readonly int Timestamp;

        [OutputConstructor]
        private DescribeTracesTraceSpanEventResult(
            ImmutableArray<Outputs.DescribeTracesTraceSpanEventAttributeResult> attributes,

            string name,

            int timestamp)
        {
            Attributes = attributes;
            Name = name;
            Timestamp = timestamp;
        }
    }
}
