// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Tls.Outputs
{

    [OutputType]
    public sealed class IndexKeyValueJsonKey
    {
        /// <summary>
        /// The key of the subfield key value index.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// Whether the filed is enabled for analysis.
        /// </summary>
        public readonly bool? SqlFlag;
        /// <summary>
        /// The type of value. Valid values: `long`, `double`, `text`.
        /// </summary>
        public readonly string ValueType;

        [OutputConstructor]
        private IndexKeyValueJsonKey(
            string key,

            bool? sqlFlag,

            string valueType)
        {
            Key = key;
            SqlFlag = sqlFlag;
            ValueType = valueType;
        }
    }
}
