// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Volcengine.Tls.Outputs
{

    [OutputType]
    public sealed class ShipperContentInfoCsvInfo
    {
        /// <summary>
        /// Delimiters are supported, including commas, tabs, vertical bars, semicolons, and Spaces.
        /// </summary>
        public readonly string Delimiter;
        /// <summary>
        /// When the field content contains a delimiter, use an escape character to wrap the field. Currently, only single quotes, double quotes, and null characters are supported.
        /// </summary>
        public readonly string EscapeChar;
        /// <summary>
        /// Configure the fields that need to be delivered.
        /// </summary>
        public readonly ImmutableArray<string> Keys;
        /// <summary>
        /// Invalid field filling content, with a length ranging from 0 to 128.
        /// </summary>
        public readonly string NonFieldContent;
        /// <summary>
        /// Whether to print the Key on the first line.
        /// </summary>
        public readonly bool PrintHeader;

        [OutputConstructor]
        private ShipperContentInfoCsvInfo(
            string delimiter,

            string escapeChar,

            ImmutableArray<string> keys,

            string nonFieldContent,

            bool printHeader)
        {
            Delimiter = delimiter;
            EscapeChar = escapeChar;
            Keys = keys;
            NonFieldContent = nonFieldContent;
            PrintHeader = printHeader;
        }
    }
}
